### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: HiveError: The box "priesttable1" is already open and of type Box<Priest>.

### ISSUE THREAD

**Issue by usernamekk** [shashiben/Flutter_cache_with_hive#2]
How can I resolve this issue. my data adding to infinite.

**Comment by usernamekk** [comment]
I tried to solve this by using Hive.close() before Hive.openBox().

**Comment by shashiben** [comment]
@usernamekk just open every box at main.dart once n don't open other boxes in any another file
