### ISSUE TITLE
Please can you help out, how to refresh new updates from api data. 

### ISSUE THREAD

**Issue by usernamekk** [shashiben/Flutter_cache_with_hive#3]
1=>first check whether there is internet connection. if there is, refresh for updates or changes, or always call the api once there is internet, update/cache data to hive, then call the hive cache data.

2=> if there is no internet connection then fall back to former hive cache data.

**Comment by shashiben** [comment]
@usernamekk  create a method for checking data n save it in separate list  and compare both list,if they are different then clean the hive box n place the new data in it ,

Note: the method needs to be called when the internet connection is there

**Comment by shashiben** [comment]
@usernamekk  if u still didnt get give me access i will look out the error
